- src/FileInputStream.cpp
- src/VPK.cpp
Fixed Linux incompatibility regarding the import of tuple in FileInputStream.cpp and changing msvc function in VPK.cpp
> Fixed Linux Incompatability.

- src/lib/VPK.cpp
... in addition to POSIX ones.
> Sanitize Windows leading directory separators

- .github/workflows/build.yml
> chore(ci): update qt

- CMakeLists.txt
- INSTALL.md
- README.md
- src/gui/Window.cpp
- src/gui/Window.h
- src/gui/dialogs/NewEntryDialog.cpp
- src/gui/dialogs/NewUpdateDialog.cpp
- src/gui/dialogs/VPKVersionDialog.cpp
> fix: add missing windows qt opengl dll

- include/vpkedit/VPK.h
- src/lib/VPK.cpp
> fix: make VPK::createFromDirectory accept relative paths

- CONTROLS.md
- src/gui/EntryTree.cpp
- src/gui/EntryTree.h
- src/gui/Window.cpp
- src/gui/Window.h
- src/gui/_gui.cmake
- src/gui/dialogs/ControlsDialog.cpp
- src/gui/dialogs/ControlsDialog.h
- src/gui/dialogs/EntryOptionsDialog.cpp
- src/gui/dialogs/EntryOptionsDialog.h
- src/gui/dialogs/NewUpdateDialog.h
- src/gui/dialogs/VPKPropertiesDialog.cpp
- src/gui/previews/DirPreview.cpp
- src/gui/previews/DirPreview.h
- src/gui/res/res.qrc
> feat: misc controls-related additions

- src/gui/EntryTree.cpp
- src/gui/Window.cpp
- src/gui/config/Options.cpp
- src/gui/config/Options.h
- Add icons to entry tree for folders and various file types, pulled from the host OS
- Add option to disable these icons
Closes #66
> feat: entry tree icons

- INSTALL.md
- LICENSE
- README.md
> feat: update INSTALL.md with new automatic alternatives

- .github/workflows/build.yml
- CMakeLists.txt
- src/gui/config/Options.cpp
- src/lib/_lib.cmake
Required for bundling into P2CE
> feat: add strata source build target to CI

- src/lib/GCF.cpp
Title explains it well i guess.
> 4GB support and support for files that have multiple starting blocks.

- .github/workflows/build.yml
- src/cli/_cli.cmake
- src/gui/_gui.cmake
Upload PDB files on Windows in Debug and Release
Closes #85
> feat: upload PDBs

- .github/workflows/release.yml
> feat: add auto-release workflow for winget repo

- src/gui/previews/VTFPreview.cpp
- src/gui/previews/VTFPreview.h
> feat: info text for basic VTF data

- .gitignore
- CMakeLists.txt
- src/libcs/libvpkedit.sln
- src/libcs/libvpkedit.test/PackFileTest.cs
- src/libcs/libvpkedit.test/libvpkedit.test.csproj
- src/libcs/libvpkedit/Attribute.cs
- src/libcs/libvpkedit/Buffer.cs
- src/libcs/libvpkedit/Constants.cs
- src/libcs/libvpkedit/Entry.cs
- src/libcs/libvpkedit/Format/BSP.cs
- src/libcs/libvpkedit/Format/FPX.cs
- src/libcs/libvpkedit/Format/GCF.cs
- src/libcs/libvpkedit/Format/GMA.cs
- src/libcs/libvpkedit/Format/GRP.cs
- src/libcs/libvpkedit/Format/PAK.cs
- src/libcs/libvpkedit/Format/PCK.cs
- src/libcs/libvpkedit/Format/VPK.cs
- src/libcs/libvpkedit/Format/ZIP.cs
- src/libcs/libvpkedit/Options.cs
- src/libcs/libvpkedit/PackFile.cs
- src/libcs/libvpkedit/PackFileType.cs
- src/libcs/libvpkedit/String.cs
- src/libcs/libvpkedit/libvpkedit.csproj
- src/libcs/libvpkedit/libvpkedit.csproj.in
I was going to make a script to upload to NuGet but honestly that can wait
> feat(libcs): create C# wrapper library

- src/gui/Window.cpp
- src/gui/Window.h
- src/gui/config/Options.cpp
- src/gui/config/Options.h
It does what it says on the tin. Automatic update notification if a newer version of VPK Edit is detected.
> feat: automatic update notification

- src/gui/FileViewer.cpp
- src/gui/_gui.cmake
- src/gui/previews/DMXPreview.cpp
- src/gui/previews/DMXPreview.h
- src/gui/previews/MDLPreview.cpp
Already have the parser done, just need to wire it up
Closes #87
> feat: DMX preview

- src/gui/EntryTree.cpp
- src/gui/Window.cpp
- src/gui/Window.h
Sets up a way for the GUI to extract virtual files
> feat: virtual entries gui base

- src/gui/EntryTree.cpp
Decrease load times by more than 50% by disabling signals during item creation process.
> Speed increase by disabling signals during item creation.

- include/vpkedit/PackFile.h
- include/vpkeditc/PackFile.h
- src/cli/Main.cpp
- src/gui/Window.cpp
- src/gui/Window.h
- src/lib/PackFile.cpp
- src/lib/detail/FileStream.cpp
- src/lib/lang/c/PackFile.cpp
- src/lib/lang/csharp/libvpkedit.test/PackFileTest.cs
- src/lib/lang/csharp/libvpkedit/PackFile.cs
- src/lib/lang/csharp/libvpkedit/libvpkedit.csproj.in
> feat: add extract functionality to lib, cli

- .github/workflows/build.yml
- INSTALL.md
- src/gui/res/i18n/vpkedit_bs_BA.ts
- src/gui/res/i18n/vpkedit_en.ts
- src/gui/res/i18n/vpkedit_es.ts
- src/gui/res/i18n/vpkedit_it.ts
- src/gui/res/i18n/vpkedit_ja.ts
- src/gui/res/i18n/vpkedit_nl.ts
- src/gui/res/i18n/vpkedit_pl.ts
- src/gui/res/i18n/vpkedit_ru_RU.ts
- src/gui/res/i18n/vpkedit_sv.ts
- src/gui/res/i18n/vpkedit_zh_CN.ts
> feat(installer): create win7 compatible standalone gui, installer

- src/cli/Main.cpp
- src/gui/Window.cpp
- src/gui/Window.h
- src/gui/previews/MDLPreview.cpp
Adds basic support for WAD3
Depends on https://github.com/craftablescience/sourcepp/pull/36
> Add WAD3 support

- src/gui/previews/TextPreview.cpp
- src/gui/previews/TextPreview.h
A kind of celebration after the Rebel Rush. (Follow me! Excuse me MEDIC, I'm in need of medical attention...!)
> Synergy EDT files

- src/gui/dialogs/VICEDialog.cpp
...That game only has *one* CTX, and it's for advertising where Ubisoft is mentioned. 😂
> Bloody Good Time's key

- src/gui/previews/TextPreview.h
> chore: add .tbl to TextPreview formats
